inherit_from:
  - "https://raw.githubusercontent.com/joeldrapper/goodcop/refs/heads/main/base.yml"

AllCops:
  TargetRubyVersion: 3.4

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Style/RedundantSelf:
  Enabled: false
