name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.4.2'

    steps:
      - name: Install D2
        run: |
          curl -L https://github.com/terrastruct/d2/releases/download/v0.6.0/d2-linux-amd64 -o d2
          chmod +x d2
          mv d2 /usr/local/bin/d2
      - name: Verify D2 Installation
        run: d2 --version
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run the default task
        run: bundle exec rake
